src/MVC.Newsreel/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC.Newsreel.Data;
using MVC.Newsreel.Services;

using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Drawing.Wordprocessing;
using PIC = DocumentFormat.OpenXml.Drawing.Pictures;
using A = DocumentFormat.OpenXml.Drawing;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace MVC.Newsreel.Controllers_
{
    public class ArticleController : Controller
    {
        private readonly Lab1dbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ArticleDataPortServiceFactory _articleDataPortServiceFactory;
        UserManager<User> _userManager;

        public ArticleController(Lab1dbContext context,
                                IWebHostEnvironment webHostEnvironment,
                                ArticleDataPortServiceFactory articleDataPortServiceFactory,
                                UserManager<User> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _articleDataPortServiceFactory = articleDataPortServiceFactory;
            _userManager = userManager;
        }

        // GET: Article
        public async Task<IActionResult> Index()
        {
            var lab1dbContext = _context.Articles.OrderByDescending(a => a.PubDate).Include(a => a.Author).Include(a => a.Category);
            return View(await lab1dbContext.ToListAsync());
        }

        // GET: Article/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .Include(a => a.Author)
                .Include(a => a.Category)
                .Include(a => a.Comments).ThenInclude(a => a.Author)
                .FirstOrDefaultAsync(m => m.ArticleId == id);
            article.Likes=_context.Likes.Where(a => a.ArticleId == article.ArticleId).Where(a => !a.IsDis).Count();
            article.Dislikes=_context.Likes.Where(a => a.ArticleId == article.ArticleId).Where(a => a.IsDis).Count();
            foreach (var item in article.Comments)
            {
                item.Likes=_context.Likes.Where(a => a.CommentId == item.CommentId).Where(a => !a.IsDis).Count();
                item.Dislikes=_context.Likes.Where(a => a.CommentId == item.CommentId).Where(a => a.IsDis).Count();
            }
            if (article == null)
            {
                return NotFound();
            }

            ViewData["ArticleId"] = new SelectList(_context.Articles, "ArticleId", "Title");
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "Name");
            var user = await _userManager.GetUserAsync(User);
            int? UserId = null;
            if (user != null)
            {
                UserId = user.Id;
            }

            var like  = await _context.Likes.FirstOrDefaultAsync(like => like.ArticleId == id && like.UserId == UserId);

            ViewData["IsLiked"] = true;
            if (like == null || (like != null && like.IsDis == true))
            {
                ViewData["IsLiked"] =  false;
            }

            ViewData["IsDisliked"] = true;
            if (like == null || (like != null && like.IsDis == false))
            {
                ViewData["IsDisliked"] =  false;
            }

            var comments  = article.Comments;

            var commentLikes = new List<bool>();
            var commentDislikes = new List<bool>();
            foreach (var comment in comments)
            {
                
                var comlike  = await _context.Likes.FirstOrDefaultAsync(like => like.CommentId == comment.CommentId && like.UserId == UserId);

                var commentLike = true;
                if (comlike == null || (comlike != null && comlike.IsDis == true))
                {
                    commentLike = false;
                }

                var commentDislike = true;
                if (comlike == null || (comlike != null && comlike.IsDis == false))
                {
                    commentDislike = false;
                }

                commentLikes.Add(commentLike);
                commentDislikes.Add(commentDislike);
            }

            ViewData["IsCommentLiked"] = commentLikes;
            ViewData["IsCommentDisliked"] = commentDislikes;

            return View(article);
        }

        // GET: Article/Create
        [Authorize(Roles="admin")]
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "Name");
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Article/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin")]
        public async Task<IActionResult> Create([Bind("ArticleId,Title,CategoryId,AuthorId,Text,Likes,Dislikes,PubDate,ImageFile")] Article article)
        {
            if (ModelState.IsValid)
            {
                if (article.ImageFile != null)
                {
                    string folder = "static/images/Article/";
                    folder += Guid.NewGuid().ToString() + "_" + article.ImageFile.FileName;
                    article.Image = "/"+folder;
                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                    await article.ImageFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }
                article.PubDate=DateTime.UtcNow;
                var user = await _userManager.GetUserAsync(User);
                article.AuthorId=user.Id;
                _context.Add(article);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "UserId", article.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", article.CategoryId);
            return View(article);
        }

        // GET: Article/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "Name", article.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", article.CategoryId);
            return View(article);
        }

        // POST: Article/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ArticleId,Title,CategoryId,AuthorId,Text,Likes,Dislikes,PubDate,ImageFile")] Article article)
        {
            if (id != article.ArticleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var our_article = _context.Articles.AsNoTracking().Where(x => x.ArticleId == id).FirstOrDefault();
                article.PubDate = our_article.PubDate;
                article.AuthorId = our_article.AuthorId;
                article.Author = _context.Users.AsNoTracking().Where(x => x.Id == our_article.AuthorId).FirstOrDefault();
                var list = article.Text.Split("\n");
                var formattedText = "";
                foreach (string i in list)
                {
                    formattedText+= "<p>" + i + "</p>";
                }
                if (article.ImageFile != null)
                {
                    string folder = "static/images/Article/";
                    folder += Guid.NewGuid().ToString() + "_" + article.ImageFile.FileName ;
                    article.Image = "/"+folder;
                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                    await article.ImageFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }
                else
                {
                    article.Image = our_article.Image;
                }
                try
                {
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.ArticleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "UserId", article.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", article.CategoryId);
            return View(article);
        }

        // GET: Article/Delete/5
        [Authorize(Roles="admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {

src/MVC.Newsreel/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC.Newsreel.Data;

namespace MVC.Newsreel.Controllers_
{
    public class UserController : Controller
    {
        private readonly Lab1dbContext _context;

        public UserController(Lab1dbContext context)
        {
            _context = context;
        }

        // GET: User
        public async Task<IActionResult> Index()
        {
            var users = await (from user in _context.Users
                        join userRole in _context.UserRoles on user.Id equals userRole.UserId
                        join role in _context.Roles on userRole.RoleId equals role.Id
                        where role.Name == "editor"
                        select user).ToListAsync();
            return View(users);
        }

        // GET: User/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            var lab1dbContext = _context.Articles.Where(a => a.AuthorId == id)
                                .OrderByDescending(a => a.PubDate)
                                .Include(a => a.Author).Include(a => a.Category);
            ViewData["Username"] = user.Name;
            return View(await lab1dbContext.ToListAsync());
        }

        public async Task<IActionResult> FavArticles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            var articleIds = await _context.Likes.Where(a => a.UserId == id && a.IsDis == false).Select(a => a.ArticleId).ToListAsync();
            var articles = await _context.Articles.Where(a => articleIds.Contains(a.ArticleId))
                                .OrderByDescending(a => a.PubDate)
                                .Include(a => a.Author).Include(a => a.Category)
                                .ToListAsync();
            ViewData["Username"] = user.Name;
            return View(articles);
        }

        public async Task<IActionResult> Profile(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            };

            return View(user);
        }

        public async Task<IActionResult> Comments(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            var lab1dbContext = _context.Comments.Where(a => a.AuthorId == id)
                                .OrderByDescending(a => a.PubDate)
                                .Include(a => a.Author).Include(a => a.Article);
            ViewData["Username"] = user.Name;
            return View(await lab1dbContext.ToListAsync());
        }

        // GET: User/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Name")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Name")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

src/MVC.Newsreel/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<MVC.Newsreel.Data.User> _userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CyberBanderka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_morph.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.Newsreel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CyberBanderka</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Статті</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Редактори</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Категорії</a>
                        </li>
                        @{
                        if (User.IsInRole("admin") || User.IsInRole("editor")){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArticleDraft" asp-action="Index">Чорнові статті</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArticleRequest" asp-action="Index">Керування статтями</a>
                        </li>
                        }}
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Правила сайту</a>
                        </li>-->
                    </ul>
                </div>
                @if(User.Identity.IsAuthenticated)
                {
                     <ul class="navbar-nav navbarchik">
                        <li class="nav-item">
                            <a class="nav-link text-dark high-heels" asp-controller="User" asp-action="Profile" 
                            asp-route-id="@_userManager.GetUserId(User)">
                                @User.Identity.Name
                            </a>
                        </li>
                        <li class="nav-item">
                            <form asp-controller="Account" asp-action="Logout">
                                    <input type="submit" value="Вихід" class="btn-size btn-login" style="font-weight:bold;"/>
                            </form>
                        </li> 
                    </ul> 
                }
                else{
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <form method="get" asp-controller="Account" asp-action="Login">
                                <input type="submit" value="Вхід" class="btn-size btn-login" style="font-weight:bold;"/>
                            </form>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <form method="get" asp-controller="Account" asp-action="Register">
                                <input type="submit" value="Реєстрація" class="btn-size btn-signup" style="font-weight:bold;"/>
                            </form>
                        </li>
                    </ul>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CyberBanderka - <a asp-area="" asp-controller="Home" asp-action="Privacy">Правила сайту</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>