src/MVC.Newsreel/Controllers/ArticleDraftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC.Newsreel.Data;

namespace MVC.Newsreel.Controllers_
{
    public class ArticleDraftController : Controller
    {
        private readonly Lab1dbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<User> _userManager;

        public ArticleDraftController(Lab1dbContext context,
                                    IWebHostEnvironment webHostEnvironment,
                                    UserManager<User> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        // GET: ArticleDraft
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Index()
        {
            var lab1dbContext = _context.ArticleDrafts.Include(a => a.Author).Include(a => a.SuggestedCategory);
            return View(await lab1dbContext.ToListAsync());
        }

        // GET: ArticleDraft/Details/5
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articleDraft = await _context.ArticleDrafts
                .Include(a => a.Author)
                .Include(a => a.SuggestedCategory)
                .FirstOrDefaultAsync(m => m.ArticleDraftId == id);
            if (articleDraft == null)
            {
                return NotFound();
            }

            return View(articleDraft);
        }

        // GET: ArticleDraft/Create
        [Authorize(Roles="admin,editor")]
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "Name");
            ViewData["SuggestedCategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: ArticleDraft/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Create([Bind("ArticleDraftId,Title,AuthorId,SuggestedCategoryId,Text,ImageFile")] ArticleDraft articleDraft)
        {
            if (ModelState.IsValid)
            {
                if (articleDraft.ImageFile != null)
                {
                    string folder = "static/images/Article/";
                    folder += Guid.NewGuid().ToString() + "_" + articleDraft.ImageFile.FileName ;
                    articleDraft.Image = "/"+folder;
                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                    await articleDraft.ImageFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }
                var user = await _userManager.GetUserAsync(User);
                articleDraft.AuthorId = user.Id;
                _context.Add(articleDraft);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "UserId", articleDraft.AuthorId);
            ViewData["SuggestedCategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", articleDraft.SuggestedCategoryId);
            return View(articleDraft);
        }

        // GET: ArticleDraft/Edit/5
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articleDraft = await _context.ArticleDrafts.FindAsync(id);
            if (articleDraft == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "Name", articleDraft.AuthorId);
            ViewData["SuggestedCategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", articleDraft.SuggestedCategoryId);
            return View(articleDraft);
        }

        // POST: ArticleDraft/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Edit(int id, [Bind("ArticleDraftId,Title,AuthorId,SuggestedCategoryId,Text,ImageFile")] ArticleDraft articleDraft)
        {
            if (id != articleDraft.ArticleDraftId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var our_article = _context.ArticleDrafts.AsNoTracking().Where(x => x.ArticleDraftId == id).FirstOrDefault();
                articleDraft.AuthorId = our_article.AuthorId;
                articleDraft.Author = _context.Users.AsNoTracking().Where(x => x.Id == our_article.AuthorId).FirstOrDefault();
                try
                {
                    if (articleDraft.ImageFile != null)
                    {
                        string folder = "static/images/Article/";
                        folder += Guid.NewGuid().ToString() + "_" + articleDraft.ImageFile.FileName ;
                        articleDraft.Image = "/"+folder;
                        string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                        await articleDraft.ImageFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                    }
                    else
                    {
                        articleDraft.Image = our_article.Image;
                    }
                    _context.Update(articleDraft);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleDraftExists(articleDraft.ArticleDraftId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "UserId", articleDraft.AuthorId);
            ViewData["SuggestedCategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", articleDraft.SuggestedCategoryId);
            return View(articleDraft);
        }

        // GET: ArticleDraft/Delete/5
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articleDraft = await _context.ArticleDrafts
                .Include(a => a.Author)
                .Include(a => a.SuggestedCategory)
                .FirstOrDefaultAsync(m => m.ArticleDraftId == id);
            if (articleDraft == null)
            {
                return NotFound();
            }

            return View(articleDraft);
        }

        // POST: ArticleDraft/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var articleDraft = await _context.ArticleDrafts.FindAsync(id);
            if (articleDraft != null)
            {
                _context.ArticleDrafts.Remove(articleDraft);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleDraftExists(int id)
        {
            return _context.ArticleDrafts.Any(e => e.ArticleDraftId == id);
        }
    }
}

src/MVC.Newsreel/Controllers/ArticleRequestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC.Newsreel.Data;

namespace MVC.Newsreel.Controllers_
{
    public class ArticleRequestController : Controller
    {
        private readonly Lab1dbContext _context;
        private readonly UserManager<User> _userManager;

        public ArticleRequestController(Lab1dbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: ArticleRequest
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Index()
        {
            var lab1dbContext = _context.ArticleRequests.Include(a => a.Article).Include(a => a.ArticleDraft).Include(a => a.Author);
            return View(await lab1dbContext.ToListAsync());
        }

        // GET: ArticleRequest/Details/5
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articleRequest = await _context.ArticleRequests
                .Include(a => a.Article)
                .Include(a => a.ArticleDraft)
                .Include(a => a.Author)
                .FirstOrDefaultAsync(m => m.ArticleRequestId == id);
            if (articleRequest == null)
            {
                return NotFound();
            }

            return View(articleRequest);
        }

        // GET: ArticleRequest/Create
        [Authorize(Roles="admin,editor")]
        public IActionResult Create()
        {
            var userName = _userManager.GetUserName(User);
            var userArticles = _context.Articles
                                .Include(a => a.Author)
                                .Where(a => a.Author.UserName == userName);
            var userArticleDrafts = _context.ArticleDrafts
                                .Include(a => a.Author)
                                .Where(a => a.Author.UserName == userName);
            ViewData["ArticleId"] = new SelectList(userArticles, "ArticleId", "Title");
            ViewData["ArticleDraftId"] = new SelectList(userArticleDrafts, "ArticleDraftId", "Title");
            return View();
        }

        // POST: ArticleRequest/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Create([Bind("ArticleRequestId,AuthorId,ArticleDraftId,ArticleId,Status")] ArticleRequest articleRequest)
        {
            var user = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                articleRequest.Status="Checking";
                articleRequest.AuthorId = user.Id;
                _context.Add(articleRequest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var userId = user.Id;
            var userArticles = _context.Articles.
                                Where(a => a.AuthorId == userId);
            var userArticleDrafts = _context.ArticleDrafts.
                                Where(a => a.AuthorId == userId);
            ViewData["ArticleId"] = new SelectList(userArticles, "ArticleId", "ArticleId", articleRequest.ArticleId);
            ViewData["ArticleDraftId"] = new SelectList(userArticleDrafts, "ArticleDraftId", "ArticleDraftId", articleRequest.ArticleDraftId);
            return View(articleRequest);
        }

        // GET: ArticleRequest/Edit/5
        [Authorize(Roles="admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articleRequest = await _context.ArticleRequests.FindAsync(id);
            if (articleRequest == null)
            {
                return NotFound();
            }
            var userArticles = _context.Articles.
                                Where(a => a.AuthorId == articleRequest.AuthorId);
            var userArticleDrafts = _context.ArticleDrafts.
                                Where(a => a.AuthorId == articleRequest.AuthorId);
            ViewData["ArticleId"] = new SelectList(userArticles, "ArticleId", "Title", articleRequest.ArticleId);
            ViewData["ArticleDraftId"] = new SelectList(userArticleDrafts, "ArticleDraftId", "Title", articleRequest.ArticleDraftId);
            return View(articleRequest);
        }

        // POST: ArticleRequest/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ArticleRequestId,AuthorId,ArticleDraftId,ArticleId,Status")] ArticleRequest articleRequest)
        {
            if (id != articleRequest.ArticleRequestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(articleRequest);
                    if (articleRequest.Status=="Approved")
                    {
                        var articleDraft = await _context.ArticleDrafts
                            .Include(a => a.SuggestedCategory)
                            .Include(a => a.Author)
                            .FirstOrDefaultAsync(m => m.ArticleDraftId == articleRequest.ArticleDraftId);
                        Article article = new Article
                        {
                            Title = articleDraft.Title,
                            Text = articleDraft.Text,
                            AuthorId = articleDraft.AuthorId,
                            Author = articleDraft.Author,
                            CategoryId = articleDraft.SuggestedCategoryId,
                            Category = articleDraft.SuggestedCategory,
                            PubDate = DateTime.UtcNow,
                            Image = articleDraft.Image,
                            ImageFile = articleDraft.ImageFile
                        };
                        _context.Add(article);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleRequestExists(articleRequest.ArticleRequestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var userArticles = _context.Articles.
                                Where(a => a.AuthorId == articleRequest.AuthorId);
            var userArticleDrafts = _context.ArticleDrafts.
                                Where(a => a.AuthorId == articleRequest.AuthorId);
            ViewData["ArticleId"] = new SelectList(userArticles, "ArticleId", "ArticleId", articleRequest.ArticleId);
            ViewData["ArticleDraftId"] = new SelectList(userArticleDrafts, "ArticleDraftId", "ArticleDraftId", articleRequest.ArticleDraftId);
            return View(articleRequest);
        }

        // GET: ArticleRequest/Delete/5
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articleRequest = await _context.ArticleRequests
                .Include(a => a.Article)
                .Include(a => a.ArticleDraft)
                .Include(a => a.Author)
                .FirstOrDefaultAsync(m => m.ArticleRequestId == id);
            if (articleRequest == null)
            {
                return NotFound();
            }

            return View(articleRequest);
        }

        // POST: ArticleRequest/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin,editor")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var articleRequest = await _context.ArticleRequests.FindAsync(id);
            if (articleRequest != null)
            {
                _context.ArticleRequests.Remove(articleRequest);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleRequestExists(int id)
        {
            return _context.ArticleRequests.Any(e => e.ArticleRequestId == id);
        }
    }
}

src/MVC.Newsreel/Views/ArticleRequest/Create.cshtml
@model MVC.Newsreel.Data.ArticleRequest

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Створити</title>
</head>
<body>

<h4>Керування статтями</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Чорнова стаття</label>
                <select asp-for="ArticleDraftId" class ="form-control" asp-items="ViewBag.ArticleDraftId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Додати" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

</body>
</html>

src/MVC.Newsreel/Views/ArticleRequest/Delete.cshtml
@model MVC.Newsreel.Data.ArticleRequest
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Видаляти</title>
</head>
<body>

<h3>Видаляти запит?</h3>
<div>
    <h4>Запит</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Статус
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            Чорнова стаття
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArticleDraft.Title)
        </dd>
        <dt class = "col-sm-2">
            Редактор
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ArticleRequestId" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>
</body>
</html>

src/MVC.Newsreel/Views/ArticleRequest/Details.cshtml
@model MVC.Newsreel.Data.ArticleRequest

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Деталі</title>
</head>
<body>

<div>
    <h4>Запит</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Article)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Article.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArticleDraft)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArticleDraft.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ArticleRequestId">Змінити</a> |
    <a asp-action="Index">Назад</a>
</div>
</body>
</html>

src/MVC.Newsreel/Views/ArticleRequest/Edit.cshtml
@model MVC.Newsreel.Data.ArticleRequest

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Редагувати</title>
</head>
<body>

<h4>Запит</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ArticleRequestId" />
            <div class="form-group">
                <label class="control-label">Статус</label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Змінити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

</body>
</html>

src/MVC.Newsreel/Views/ArticleRequest/Index.cshtml
@model IEnumerable<MVC.Newsreel.Data.ArticleRequest>
    
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Керування статтями</title>
</head>
<body>
<p>
    <a asp-action="Create">Додати новий запит</a>
</p>
<div class="artreq-container">
@foreach (var item in Model) {
<div class="artreq-cards">
    <div class="artreq-card-body">
        <strong>Статус: </strong>@Html.DisplayFor(modelItem => item.Status)
        <a asp-controller="ArticleDraft" asp-action="Details" asp-route-id="@item.ArticleDraftId">
            <h5 class="mb-0">@Html.DisplayFor(modelItem => item.ArticleDraft.Title)</h5></a>
        <label>@Html.DisplayFor(modelItem => item.Author.Name)</label>
        @{
        if (User.IsInRole("admin"))
        {
            <div>
                <a asp-action="Edit" asp-route-id="@item.ArticleRequestId">Змінити</a> |
                <a asp-action="Delete" asp-route-id="@item.ArticleRequestId">Видаляти</a>
            </div>
        }
        }
    </div>
</div>
}
</div>
</body>
</html>